WARNING: Ignoring invalid distribution -erminado (/mnt/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -cipy (/mnt/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages)
Traceback (most recent call last):
  File "acv_el_surrogate.py", line 164, in <module>
    best = fmin(acv_classifier_optimisation, verbose=0, space = space, algo=rand.suggest, max_evals = 50, trials=trials, 
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/hyperopt/fmin.py", line 507, in fmin
    return trials.fmin(
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/hyperopt/base.py", line 682, in fmin
    return fmin(
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/hyperopt/fmin.py", line 271, in run
    new_ids, self.domain, trials, self.rstate.randint(2 ** 31 - 1)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
